### ISSUE TITLE
Question on Comparison with SOTA works

### ISSUE THREAD

**Issue by avegetablechicken** [zhangy76/PhysPT#10]
Thank you for your amazing work! You said in your paper that results of some SOTA works are evaluated on 3D joints computed from fitted body models (Mosh) instead of the one provided in the original datasets. Could you please describe how you did that? Especially to code that cannot run properly like D&D?

**Comment by zhangy76** [comment]
I just use the 3D joint annotations provided in the original datasets, although this leads to higher reconstruction errors.

**Comment by avegetablechicken** [comment]
Does it mean that you successfully ran D&D's code compare their results with relative datasets?

**Comment by zhangy76** [comment]
oh, I see, I directly use their reported results
