### ISSUE TITLE
Questions on data processing

### ISSUE THREAD

**Issue by chenshuoZhang** [zhangy76/PhysPT#4]
Thank you for your excellent work! I'm having a bit of a problem using your code (mainly smpl_phys.py) to process the data. When I proceeded to the optimization problem in *3.2.4 Physics-inspired Training Losses* in the paper, I didn't find the details of the linear inequality constraint specified on $x_t$ (i.e. the value of $\overline{x}_{max}$). I would appreciate it if you could provide the relevant details or tell me where I should find them!

**Comment by zhangy76** [comment]
Thanks for your interests! We set the range to be 10-1010 so that the contact forces roughtly equal to the gravitational forces under normal standing as https://github.com/zhangy76/PhysPT/blob/ed3680b36029adb4e3bdd27a0934773c3d0db06b/models/PhysPT.py#L183.

**Comment by zhangy76** [comment]
Close as being inactive, feel free to open again
