### ISSUE TITLE
Question on used SMPL model

### ISSUE THREAD

**Issue by PemasiriAkila** [zhangy76/PhysPT#5]
Thank you for your amazing work! I have a difficult time in figuring out what is the exact SMPL model used here. I understand that the code uses SMPL (and not SMPLX) as many of the dimensions contains X:6890:3. Also the code refers to the attributes of "V_regressor" and "kintree_table_J" which are not in the SMPL model. 

Thanks in advance.

**Comment by zhangy76** [comment]
The current implementation support SMPL and SMPL-H, which both have the dimensions X:6890:3. I made some changes to the original model file. So you may directly download the model from the provided link instead of the original model. Please let me know if additional information is needed. Thanks

**Comment by PemasiriAkila** [comment]
Thank you very much for the reply. It works.
