### ISSUE TITLE
Phys-SMPL For Different Masses

### ISSUE THREAD

**Issue by PemasiriAkila** [zhangy76/PhysPT#6]
Hi, it appears that the physics information is constant for all the examples (e.g. volumn, mass, inertia, mass_scaling) which are directly read from the physics.pkl. Can you please provide an example of using compute_massinertia, where I assume the mass is updated.

**Comment by zhangy76** [comment]
The function takes as input v_shaped: Nx6890x3 and joints_smpl: Nx24x3 and outputs the updated mass. For v_shaped and  joints_smpl, they are vertex and joint positions produced from the SMPL.

**Comment by EnnaSachdeva** [comment]
Could you please explain what N represents here?Is it Batch size?

**Comment by zhangy76** [comment]
yes, it is batch size
