### ISSUE TITLE
version of required libraries

### ISSUE THREAD

**Issue by taggeli** [zhangy76/PhysPT#7]
Hi, I have a hard time finding compatible versions for the required libraries. Which versions did you use for the required libraries and PyQt5?

**Comment by zhangy76** [comment]
can you try PyQt5  5.15.6?

**Comment by taggeli** [comment]
How about the versions of the rest of the libraries? There seems to be a dependency between opencv and pyqt5.

**Comment by zhangy76** [comment]
I use opencv-python 4.3.0.36. As PyQt5 is only utilized in visualization, you may consider set up a new environment only for the visualization part.
