### ISSUE TITLE
Question on smpl_phys.py

### ISSUE THREAD

**Issue by chkim1011** [zhangy76/PhysPT#8]
Hello!
Thank you for your amazing work!!

I have a question regarding this particular line in your code:

https://github.com/zhangy76/PhysPT/blob/ed3680b36029adb4e3bdd27a0934773c3d0db06b/models/smpl_phys.py#L142

In this method, you used v_shaped and joints_smpl that v_shaped is "unposed" vertices and joints_smpl is "posed". Could you explain why you used v_shaped as a inputs? 

Thank you for your time and consideration!

**Comment by zhangy76** [comment]
Thanks for the interests. v_shaped will be only in computing the base physical parameters that are invariant under different poses. On the other hand, the physical parameters that function of the poses will be computed with "posed" information.

**Comment by chkim1011** [comment]
Thank you!
