### ISSUE TITLE
Camera Paramter

### ISSUE THREAD

**Issue by Bugjudger** [zhangy76/PhysPT#9]
Hi, thanks for sharing this great job. I want to align the viewpoint of SMPL with the original image, so how can I find the correct camera parameter of SMPL? Or can we use other methods to align them?

**Comment by zhangy76** [comment]
Thanks. Current visualization code does not support this but you may considering aligning the model with the estimation from  the kinematics approaches.

**Comment by zhangy76** [comment]
Close as being inactive, feel free to open again.
